# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
    ]
