# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180327_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechprofile',
            name='sprofile_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
