# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180427_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brake_issues', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Poor braking'), ('N', 'Noises while braking'), ('B', 'Brake warning light is on'), ('H', 'Handbrake is not effective'), ('M', 'ABS malfunction'), ('S', 'Speed sensor issue')], max_length=6)),
                ('suspension_issues', multiselectfield.db.fields.MultiSelectField(choices=[('V', 'Vehicle pulls to one side'), ('B', 'Bumpy ride')], max_length=2)),
                ('steering_ride_issues', multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Steering wheel vibrates'), ('B', 'Bumpy ride')], max_length=2)),
                ('engine_issues', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Engine not starting'), ('S', 'Slow Cranking'), ('l', 'Engine check light is on'), ('H', 'Engine is over heating'), ('P', 'Poor vehicle pickup'), ('R', 'Rough engine'), ('F', 'Inspection fluid leak'), ('E', 'Exhaust and pollution check')], max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='car_make',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='Part_Cost',
            field=models.IntegerField(help_text='price of car part', null=True),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='service',
            field=models.PositiveSmallIntegerField(choices=[('1', 'PanelBeating'), ('2', 'ElectricalWiring'), ('3', 'Engine'), ('4', 'Painting'), ('5', 'GeneralMaintenance')]),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='service_cost',
            field=models.IntegerField(help_text='total cost of repair', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_model',
            field=models.CharField(blank=True, help_text='ex LandCruiser', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.CarMake'),
            preserve_default=False,
        ),
    ]
