# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180327_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(null=True)),
                ('mechanic_name', models.CharField(max_length=20)),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'PanelBeating'), ('W', 'ElectricalWiring'), ('E', 'Engine'), ('Pa', 'Painting'), ('G', 'GeneralMaintenance')], max_length=5)),
                ('garage_location', models.CharField(help_text='location where car has been serviced', max_length=255)),
                ('New_Car_Part', models.CharField(help_text='New car part replaced', max_length=255)),
                ('Part_Cost', models.IntegerField(help_text='price of car part')),
                ('location', models.CharField(max_length=20)),
                ('repair_done', models.TextField(help_text='small description of repair done', max_length=1000)),
                ('service_cost', models.IntegerField(help_text='total cost of repair')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='quizzes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='student',
        ),
        migrations.RenameField(
            model_name='mechprofile',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='name',
        ),
        migrations.AddField(
            model_name='mechprofile',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TakenQuiz',
        ),
        migrations.AddField(
            model_name='review',
            name='mechprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MechProfile'),
        ),
    ]
