# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mechprofile_sprofile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechprofile',
            old_name='sprofile_photo',
            new_name='profile_photo',
        ),
    ]
