# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180327_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechprofile',
            name='profile_photo',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
