# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180811_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechprofile',
            old_name='dental_removal',
            new_name='dent_removal',
        ),
    ]
