# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:44
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180501_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carhistory',
            name='service',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'PanelBeating'), ('W', 'ElectricalWiring'), ('E', 'Engine'), ('P', 'Painting'), ('G', 'GeneralMaintenance')], max_length=9),
        ),
        migrations.AlterField(
            model_name='repair',
            name='brake_issues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Poor braking'), ('N', 'Noises while braking'), ('B', 'Brake warning light is on'), ('H', 'Handbrake is not effective'), ('M', 'ABS malfunction'), ('S', 'Speed sensor issue')], max_length=11),
        ),
        migrations.AlterField(
            model_name='repair',
            name='engine_issues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Engine not starting'), ('S', 'Slow Cranking'), ('l', 'Engine check light is on'), ('H', 'Engine is over heating'), ('P', 'Poor vehicle pickup'), ('R', 'Rough engine'), ('F', 'Inspection fluid leak'), ('E', 'Exhaust and pollution check')], max_length=15),
        ),
        migrations.AlterField(
            model_name='repair',
            name='steering_ride_issues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Steering wheel vibrates'), ('B', 'Bumpy ride')], max_length=3),
        ),
        migrations.AlterField(
            model_name='repair',
            name='suspension_issues',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('V', 'Vehicle pulls to one side'), ('B', 'Bumpy ride')], max_length=3),
        ),
    ]
