# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180327_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(auto_now_add=True)),
                ('mechanic_name', models.CharField(max_length=20)),
                ('service', multiselectfield.db.fields.MultiSelectField(choices=[('P', 'PanelBeating'), ('W', 'ElectricalWiring'), ('E', 'Engine'), ('Pa', 'Painting'), ('G', 'GeneralMaintenance')], max_length=5)),
                ('garage_location', models.CharField(help_text='location where car has been serviced', max_length=255)),
                ('New_Car_Part', models.CharField(help_text='New car part replaced', max_length=255)),
                ('Part_Cost', models.IntegerField(help_text='price of car part')),
                ('location', models.CharField(max_length=20)),
                ('repair_done', models.TextField(help_text='small description of repair done', max_length=1000)),
                ('service_cost', models.IntegerField(help_text='total cost of repair')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
