# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180501_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painting_issues', multiselectfield.db.fields.MultiSelectField(choices=[('U', 'Undercoat Finishes'), ('B', 'Base Coat Paints'), ('A', 'Acyrlic lacquers'), ('C', 'Clear Coat finishes'), ('F', 'Full Body Painting'), ('D', 'Dental Removals'), ('R', 'Dry Dent removal on bumpers'), ('E', 'Exhaust pipe welding/repair'), ('W', 'Water leaks')], max_length=17)),
                ('other', models.TextField(blank=True, max_length=3000)),
            ],
        ),
    ]
