# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_painting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_service', multiselectfield.db.fields.MultiSelectField(choices=[('B', 'Wheel Balancing'), ('R', 'Wheel Rotation'), ('A', 'Wheel Alignment')], max_length=5)),
                ('periodic_service', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Engine Oil'), ('O', 'Oil filter'), ('A', 'Air Filter'), ('B', 'Breake'), ('Cl', 'Clutch'), ('C', 'Coolant')], max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='carhistory',
            name='name',
        ),
        migrations.AlterField(
            model_name='painting',
            name='other',
            field=models.TextField(blank=True, help_text='other', max_length=3000),
        ),
        migrations.DeleteModel(
            name='CarHistory',
        ),
    ]
