# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_carhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carhistory',
            name='service_date',
        ),
    ]
