# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_carhistory_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhistory',
            name='service_date',
            field=models.DateTimeField(null=True),
        ),
    ]
