# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180504_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechprofile',
            name='profile_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
