# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180404_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
