# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180514_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, help_text='ex Car,Lorry', max_length=255),
        ),
    ]
