# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='mechprofile',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
