# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_mechprofile_dental_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechprofile',
            name='estate',
            field=models.CharField(default=1, help_text='ex SouthB,Bahati', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechprofile',
            name='town',
            field=models.CharField(default=1, help_text='ex Nairobi,Nakuru,Rongai', max_length=250),
            preserve_default=False,
        ),
    ]
