# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180522_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRepairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('car_model', models.CharField(max_length=200)),
                ('license_plate', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('Charges', models.IntegerField(max_length=10)),
                ('Issue', models.TextField(max_length=1000)),
            ],
        ),
    ]
