# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_clientrepairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrepairs',
            name='Charges',
        ),
    ]
