# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_clientrepairs_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechprofile',
            name='car_spa',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechprofile',
            name='general_service',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechprofile',
            name='interior_detailing',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
