# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180606_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Painting',
        ),
        migrations.DeleteModel(
            name='RegularService',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Repair',
        ),
    ]
