# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='regular_maintenance',
            field=models.TextField(help_text='update on regular maintenance', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_type',
            field=models.TextField(help_text='type of repair done', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='replace_part',
            field=models.TextField(help_text='part replaced', max_length=500, null=True),
        ),
    ]
