# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180612_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='regular_maintenance',
            field=models.TextField(blank=True, default=1, help_text='update on regular maintenance', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_type',
            field=models.TextField(blank=True, default=1, help_text='type of repair done', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair',
            name='replace_part',
            field=models.TextField(blank=True, default=1, help_text='part replaced', max_length=500),
            preserve_default=False,
        ),
    ]
